---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

# inputs:
#   - name: task-scripts
inputs:
    - name: subject
    - name: master-pipeline

run:
  path: ./master-pipeline/ci/tasks/build.sh
    # path: echo
    # args: [hello world]