---
platform: linux

image_resource:
  type: docker-image
  source: {repository: busybox}

# inputs:
#   - name: task-scripts
inputs:
    - name: subject

run:
#   path: subject/ci/pre-build.sh
    path: echo
    args: [hello world]