---
resources:
  - name: master-pipeline
    type: git
    source:
      uri: https://github.com/jshingler/Concourse-Master-Pipeline.git
  - name: subject
    type: git
    source:
      uri: https://github.com/jshingler/((subject)).git

jobs:
  - name: build
    public: true
    plan:
      - get: master-pipeline
      - get: subject
      - task: pre-build
        file: master-pipeline/ci/tasks/pre-build.yml
    #   - task: build
    #     file: master-pipeline/ci/tasks/build.yml
    #   - task: pre-build
    #     file: master-pipeline/ci/tasks/post-build.yml
